### ISSUE TITLE
OpenAPI Specification vs. Swagger specification - Why the change in capitalization for Specification?

### ISSUE THREAD

**Issue by coopr** [OAI/OpenAPI-Style-Guide#6]
I find it curious that the word "specification" is capitalized when following OpenAPI, but not when following Swagger.

I understand there exists an abbreviation OAS - but I'm not sure that the presence of a capital S in that abbreviation necessitates a capital S in "OpenAPI Specification". 

Is there an explanation for why Specification is capitalized?

**Comment by earth2marsh** [comment]
Because both an initiative and a specification can be referred to as `OpenAPI`, those two nouns were made part of the proper names of those two things in order to make it easier to differentiate between them.

FWIW, it's acceptable to refer to specifications (documents, not the Spec itself) in the OpenAPI format using lowercase. The capital is only needed when describing the formal API description format known as the OpenAPI Specification (OAS).

Does that help?
